import { type DirectorioUser } from "./directorio-schema";

export const directorioData: DirectorioUser[] = [
  {
    id: "1",
    nombre: "Ana García Martínez",
    puesto: "Directora de Operaciones",
    ubicacion: "Madrid",
    correo: "a.garcia@gruposiete.es",
    telefono: "+34 91 432 10 00",
  },
  {
    id: "2",
    nombre: "Carlos López Ruiz",
    puesto: "Responsable de TI",
    ubicacion: "Barcelona",
    correo: "c.lopez@gruposiete.es",
    telefono: "+34 93 217 45 12",
  },
  {
    id: "3",
    nombre: "María Fernández Sánchez",
    puesto: "Jefa de Recursos Humanos",
    ubicacion: "Madrid",
    correo: "m.fernandez@gruposiete.es",
    telefono: "+34 91 432 10 21",
  },
  {
    id: "4",
    nombre: "Pablo Rodríguez Torres",
    puesto: "Técnico de Infraestructura",
    ubicacion: "Valencia",
    correo: "p.rodriguez@gruposiete.es",
    telefono: "+34 96 315 78 34",
  },
  {
    id: "5",
    nombre: "Laura Gómez Blanco",
    puesto: "Coordinadora de Proyectos",
    ubicacion: "Sevilla",
    correo: "l.gomez@gruposiete.es",
    telefono: "+34 95 487 23 67",
  },
  {
    id: "6",
    nombre: "Javier Martínez Díaz",
    puesto: "Desarrollador Senior",
    ubicacion: "Barcelona",
    correo: "j.martinez@gruposiete.es",
    telefono: "+34 93 217 45 88",
  },
  {
    id: "7",
    nombre: "Sofía Navarro Pons",
    puesto: "Diseñadora UX/UI",
    ubicacion: "Barcelona",
    correo: "s.navarro@gruposiete.es",
    telefono: "+34 93 217 46 05",
  },
  {
    id: "8",
    nombre: "Andrés Moreno Vega",
    puesto: "Responsable Comercial",
    ubicacion: "Madrid",
    correo: "a.moreno@gruposiete.es",
    telefono: "+34 91 432 10 54",
  },
  {
    id: "9",
    nombre: "Elena Jiménez Castro",
    puesto: "Contable Senior",
    ubicacion: "Bilbao",
    correo: "e.jimenez@gruposiete.es",
    telefono: "+34 94 423 89 10",
  },
  {
    id: "10",
    nombre: "Iñaki Etxeberria Elorza",
    puesto: "Responsable de Sede",
    ubicacion: "Bilbao",
    correo: "i.etxeberria@gruposiete.es",
    telefono: "+34 94 423 89 22",
  },
  {
    id: "11",
    nombre: "Patricia Alonso Ramos",
    puesto: "Técnica de Soporte",
    ubicacion: "Madrid",
    correo: "p.alonso@gruposiete.es",
    telefono: "+34 91 432 11 78",
  },
  {
    id: "12",
    nombre: "Roberto Serrano Gil",
    puesto: "Analista de Datos",
    ubicacion: "Valencia",
    correo: "r.serrano@gruposiete.es",
    telefono: "+34 96 315 78 91",
  },
  {
    id: "13",
    nombre: "Carmen Ruiz Herrera",
    puesto: "Directora de Marketing",
    ubicacion: "Sevilla",
    correo: "c.ruiz@gruposiete.es",
    telefono: "+34 95 487 24 33",
  },
  {
    id: "14",
    nombre: "Miguel Ángel Torres Vidal",
    puesto: "Arquitecto de Software",
    ubicacion: "Barcelona",
    correo: "ma.torres@gruposiete.es",
    telefono: "+34 93 217 47 19",
  },
  {
    id: "15",
    nombre: "Nuria Castillo Peña",
    puesto: "Administrativa",
    ubicacion: "Madrid",
    correo: "n.castillo@gruposiete.es",
    telefono: "+34 91 432 10 03",
  },
];
